
package booksservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookWSService", targetNamespace = "http://booksservice/", wsdlLocation = "http://localhost:8585/BookWS?wsdl")
public class BookWSService
    extends Service
{

    private final static URL BOOKWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKWSSERVICE_EXCEPTION;
    private final static QName BOOKWSSERVICE_QNAME = new QName("http://booksservice/", "BookWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/BookWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKWSSERVICE_WSDL_LOCATION = url;
        BOOKWSSERVICE_EXCEPTION = e;
    }

    public BookWSService() {
        super(__getWsdlLocation(), BOOKWSSERVICE_QNAME);
    }

    public BookWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKWSSERVICE_QNAME, features);
    }

    public BookWSService(URL wsdlLocation) {
        super(wsdlLocation, BOOKWSSERVICE_QNAME);
    }

    public BookWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKWSSERVICE_QNAME, features);
    }

    public BookWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookWs
     */
    @WebEndpoint(name = "BookWsPort")
    public BookWs getBookWsPort() {
        return super.getPort(new QName("http://booksservice/", "BookWsPort"), BookWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookWs
     */
    @WebEndpoint(name = "BookWsPort")
    public BookWs getBookWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://booksservice/", "BookWsPort"), BookWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKWSSERVICE_EXCEPTION!= null) {
            throw BOOKWSSERVICE_EXCEPTION;
        }
        return BOOKWSSERVICE_WSDL_LOCATION;
    }

}
